### ISSUE TITLE
License policy?

### ISSUE THREAD

**Issue by yoshiso** [Nmerrillvt/kPCA#3]
Hi @Nmerrillvt,

I was impressed to see your implementation and result! Here I have one question, do you have any license policy for your implementation? Such as MIT, Apache 2.0 etc.

**Comment by Nmerrillvt** [comment]
Hi Sho,

I made this for a class project, I don't have any particular license
associated with it. Feel free to use it in anyway you need.

Nick

**Comment by yoshiso** [comment]
Thanks for your reply and great to hear about it!
